syntax = "proto3";

package bridge;

option go_package = "proton_go_api_bridge/native/protobuf/bridge";

import "commands/commands.proto";
import "results/results.proto";

message Command {
  oneof command {
    commands.Login login = 1;
  }
}

message Result {
  oneof response {
    results.Error                          error                             = 1;
    results.LoginSuccess                   login_success                     = 2;
    results.LoginHumanVerificationRequired login_human_verification_required = 3;
    results.Login2FARequired               login_2fa_required                = 4;
  }
}
