syntax = "proto3";

package results;

option go_package = "proton_go_api_bridge/native/protobuf/results";

message Error {
  string message = 1;
}

message Login {
  message Session {
    string uid           = 1;
    string user_id       = 2;
    string access_token  = 3;
    string refresh_token = 4;
  }

  message Success {
    Session session = 1;
  }

  message HumanVerificationRequired {
    string uri = 1;
  }

  message TwoFactorRequired {
    bool totp_enabled = 1;
    // TODO: Fido2
    // bool fido_enabled = 2;
    // stuff fido_config = 3;
    Session session = 4;
  }

  message TwoFactorSuccess {}

  oneof outcome {
    Success                   success                     = 1;
    HumanVerificationRequired human_verification_required = 2;
    TwoFactorRequired         two_factor_required         = 3;
    TwoFactorSuccess          two_factor_success          = 4;
  }
}
